[cursor]
style = "Beam"
vi_mode_style.shape = "Beam"

[mouse]
hide_when_typing = true

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.4
blur = true
decorations = "Buttonless"

[window.padding]
x = 0
y = 0

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#181818"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
